![Algoritmos e Estrutura de Dados II - Prof Piva](AED2_banner.jpg)

## Aula 6 - Pilhas

### Primeira Implementação

In [1]:
# Implementacao da classe Pilha
class Stack:
    # Inicia com uma pilha vazia
    def __init__(self):
        self.itens = []
    
    # Verifica se pilha esta vazia
    def is_empty(self):
        return self.itens == []
    
    # Adiciona elemento no topo (topo e o final da lista)
    def push(self, item):
        self.itens.append(item)
        print(f"PUSH {item}")

    # Remove elemento do topo (final da lista)
    def pop(self):
        print("POP")
        return self.itens.pop()
    
    # Obtem o elemento do topo (mas nao remove)
    def peek(self):
    # Em Python, indice -1 retorna ultimo elemento (topo)
        return self.itens[-1]
    
    # Retorna o numero de elementos da pilha
    def size(self):
        return len(self.itens)
    
    # Imprime pilha na tela
    def print_stack(self):
        print(self.itens)

In [2]:
# TESTANDO
S = Stack()

In [3]:
S.print_stack()

[]


In [4]:
S.push(1)

PUSH 1


In [5]:
S.push(2)

PUSH 2


In [6]:
S.push(3)

PUSH 3


In [7]:
S.print_stack()

[1, 2, 3]


In [8]:
S.pop()

POP


3

In [9]:
S.pop()

POP


2

In [10]:
S.print_stack()

[1]


In [11]:
S.push(7)

PUSH 7


In [12]:
S.push(8)

PUSH 8


In [13]:
S.push(9)

PUSH 9


In [14]:
S.print_stack()

[1, 7, 8, 9]


In [15]:
print(S.is_empty())

False


### Segunda Implementação

In [16]:
import numpy as np

In [17]:
class Pilha:
    def __init__(self, capacidade):
        self.__capacidade = capacidade
        self.__topo = -1
        self.__valores = np.zeros(self.__capacidade, dtype=int)

    def __pilha_cheia(self):
        if self.__topo == self.__capacidade - 1:
            return True
        else:
            return False
    
    def __pilha_vazia(self):
        if self.__topo == -1:
            return True
        else:
            return False
    
    def empilhar(self, valor):
        if self.__pilha_cheia():
            print('A pilha está cheia')
        else:
            self.__topo += 1
            self.__valores[self.__topo] = valor
    
    def desempilhar(self):
        if self.__pilha_vazia():
            print('A pilha está vazia')
        else:
            self.__valores[self.__topo] = 0
            self.__topo -= 1
    
    def ver_topo(self):
        if self.__topo != -1:
            return self.__valores[self.__topo]
        else:
            return -1
    
    # Imprime pilha na tela
    def imprime_pilha(self):
        print(self.__valores)

In [18]:
pilha = Pilha(5)

In [19]:
pilha.imprime_pilha()

[0 0 0 0 0]


In [20]:
pilha.ver_topo()

-1

In [21]:
pilha.empilhar(1)
pilha.ver_topo()

np.int64(1)

In [22]:
pilha.empilhar(1)
pilha.empilhar(2)
pilha.empilhar(3)
pilha.empilhar(4)

In [23]:
pilha.imprime_pilha()

[1 1 2 3 4]


In [24]:
pilha.empilhar(6)

A pilha está cheia


In [25]:
pilha.ver_topo()

np.int64(4)

In [26]:
pilha.desempilhar()

In [27]:
pilha.ver_topo()

np.int64(3)

In [28]:
pilha.desempilhar()
pilha.desempilhar()
pilha.desempilhar()

In [29]:
pilha.ver_topo()

np.int64(1)

In [30]:
pilha.imprime_pilha()

[1 0 0 0 0]


In [31]:
pilha.desempilhar()

In [32]:
pilha.imprime_pilha()

[0 0 0 0 0]


In [33]:
pilha.desempilhar()

A pilha está vazia


# Vamos à Prática!
## Exercício

Utilização de pilhas para conversão de números inteiros em decimal para binário (método da divisão sucessiva por 2).

**Utilização do classe Stack..**

In [34]:
# Função que converte um número decimal para binário
def decimal_binario(numero):
 s = Stack()
 while numero > 0:
     resto = numero % 2
     s.push(resto)
     numero = numero // 2
 binario = ''
 while not s.is_empty():
     binario = binario + str(s.pop())
 return binario

### Testando!
233 --> binário

In [36]:
# TESTANDO
n = int(input('Entre com um número inteiro: '))
print(f"O valor {n} em binário é: {decimal_binario(n)}") 

Entre com um número inteiro:  27676


PUSH 0
PUSH 0
PUSH 1
PUSH 1
PUSH 1
PUSH 0
PUSH 0
PUSH 0
PUSH 0
PUSH 0
PUSH 1
PUSH 1
PUSH 0
PUSH 1
PUSH 1
POP
POP
POP
POP
POP
POP
POP
POP
POP
POP
POP
POP
POP
POP
POP
O valor 27676 em binário é: 110110000011100


### Fim Teoria Aula 6